validate with scitokens-verify if it is available

diff --git a/httokendecode b/httokendecode
--- a/httokendecode
+++ b/httokendecode
@@ -10,11 +10,12 @@ usage()
     echo
     echo 'Decodes a JSON Web Token'
     echo '  -a: show algorithm portion of JWT'
-    echo '  -H: show dates in human readable format instead of epoch '
+    echo '  -H: show dates in human readable format instead of epoch'
     echo 'File name may be "-" to read from stdin.'
     echo 'If file name not given, follows WLCG Bearer Token Discovery'
     echo '  which is to first try $BEARER_TOKEN, next $BEARER_TOKEN_FILE,'
     echo '  and next ${XDG_RUNTIME_DIR:-/tmp}/bt_u`id -u`.'
+    echo 'If scitokens-verify is available, will also validate the token.'
     exit 1
 } >&2
 
@@ -124,4 +125,19 @@ if "$HUMANDATE"  ; then
    echo $READABLE | jq .
 else
    echo "$JWT" | jq .
+fi
+
+set +e
+VERIFY="$(command -v scitokens-verify)"
+if [ $? != 0 ]; then
+    # silently exit if scitokens-verify not found
+    exit
+fi
+VERIFYOUT="$($VERIFY $TOKEN)"
+RET=$?
+if [ $RET != 0 ]; then
+    if [ -n "$VERIFYOUT" ]; then
+        echo "$VERIFYOUT" >&2
+    fi
+    exit $RET
 fi
